### ISSUE TITLE
v2.1.1 cause throw error：[vuex] Do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by lerit** [vuejs/vue-hot-reload-api#58]
i upgrade vue-loader to "13.3.0",my project throw error(vuex options:{strict:true}):
[vuex] Do not mutate vuex store state outside mutation handlers.
![02](https://user-images.githubusercontent.com/4743467/31749888-3b601b10-b4af-11e7-8c26-3f0233f4232e.png)
it give me nothing useful info,so my only work is to recover the previous git version and analyze it.
my project work fine for long time,except updage package,i change nothing.
i analyze the vue-loader and its dependencies(vue-hot-reload-api,and so on),and replace with previous version,finally i find the vue-hot-reload-api@2.1.0 is the last work fine version.
i really do not know where my code cause this problem,so has no Reproduction Step.
i think it maybe relate to vue-router,because the error was throw after click menu,and because the error trace tell me it begin from vue-router.esm.js(function extracetGuard)

but i promise if i replace vue-hot-reload-api@2.2.0 to vue-hot-reload-api@2.1.0,all work fine.
and i also expect the vuex can throw more useful info to help me locate my problem

**Comment by lerit** [comment]
this is the full error info:
![03](https://user-images.githubusercontent.com/4743467/31750284-9d6a24f2-b4b1-11e7-97a9-f3802e0ccbff.png)
maybe the common ground is  begin from Vue.exntend?

**Comment by yyx990803** [comment]
In 2.1.1 of `vue-hot-reload-api` options are now turned into constructors in a lazy fashion, so if you made it reactive before actually rendering the component, `Vue.extend` will be considered performing reactive updates when it mutates the options in order to normalize it.

However, this only happens because you made your component options object reactive by storing it as part of store state. This is definitely something you want to avoid - store state should be plain data for proper serialization, and you should avoid placing components in it.

**Comment by lerit** [comment]
thank you very much!
i will modify my code.
but in fact,i can not understand what's you mean.can you give me a sample that can lead to this problem?because vuex give me useless info,so it hard to location the error.
thanks!

**Comment by yyx990803** [comment]
e.g.

``` js
import Foo from 'foo'

export default new Vuex.Store({
  state: {
    Foo
  }
})
```

This will cause the `Foo` component object to be considered part of the store's state.

**Comment by bitqiang** [comment]
Can I think that it is not the import data as the state data source？
The data in state should be defined in advance.

**Comment by bitqiang** [comment]
@yyx990803
